website/detail/urls.py
from django.conf.urls import url
from django.contrib import admin

from .views import (
		index,
		signup,
		details,
		Login,
		home,
		gallery,
		logIn,
		signcheck,
		auth_view,
		logOut,
		formcheck,
		formcheck2,
		formcheck3,
		formcheck4,
		member,
		feedbackmake,
		contact,
		commentmake,
	)

urlpatterns = [
    url(r'^$', index),
    url(r'^signup/$', signup),
    url(r'^signUp/$', signcheck),
    url(r'^details/$', details),
    url(r'^Details/$', formcheck),

    url(r'^login/$', Login),
   	url(r'^logIn/$', logIn),
    url(r'^auth/$', auth_view),
    url(r'^logout/$', logOut),

    url(r'^home/$', home),
    url(r'^gallery/$', gallery),
    url(r'^members/$', member),
    url(r'^feedback/$', feedbackmake),
    url(r'^Contact/$', formcheck2),
    url(r'^contact/$', contact),
    url(r'^comment/$', commentmake),
    url(r'^Comment/$', formcheck3),
    url(r'^Comment/$', formcheck3),
    url(r'^Feedback/$', formcheck4),
    
  ]

website/website/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include("detail.urls")),
]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

website/detail/models.py
from __future__ import unicode_literals
from django.db import models


class Detail(models.Model):
	username = models.CharField(max_length = 20)
	firstname = models.CharField(max_length = 20)
	lastname = models.CharField(max_length = 20)
	dob = models.CharField(max_length = 20)
	gender = models.CharField(max_length = 10)
	contact = models.CharField(max_length = 10)
	address = models.CharField(max_length = 30)
	highschool = models.CharField(max_length = 5)
	intermediate = models.CharField(max_length = 5)
	schoolname = models.CharField(max_length = 30)
	schoolplace = models.CharField(max_length = 20)
	occupation =  models.CharField(max_length = 20)
	updated = models.DateTimeField(auto_now  = True, auto_now_add = False)
	timestamp = models.DateTimeField(auto_now  = False, auto_now_add = True)

	def __unicode__(self):
		return self.firstname

	def __str__(self):
		return self.firstname



class contactus(models.Model):
	username = models.CharField(max_length = 20)
	message = models.TextField(max_length = 1000)
	updated = models.DateTimeField(auto_now  = True, auto_now_add = False)
	timestamp = models.DateTimeField(auto_now  = False, auto_now_add = True)

	def __unicode__(self):
		return self.username

	def __str__(self):
		return self.username

class stories(models.Model):
	id = models.AutoField(primary_key=True)
	username = models.CharField(max_length = 20)
	story = models.TextField(max_length = 1000)
	updated = models.DateTimeField(auto_now  = True, auto_now_add = False)
	timestamp = models.DateTimeField(auto_now  = False, auto_now_add = True)

	def __unicode__(self):
		return self.username

	def __str__(self):
		return self.username

class comment(models.Model):
	id = models.AutoField(primary_key=True)
	username = models.CharField(max_length = 20)
	comment = models.TextField(max_length = 1000)
	updated = models.DateTimeField(auto_now  = True, auto_now_add = False)
	timestamp = models.DateTimeField(auto_now  = False, auto_now_add = True)

	def __unicode__(self):
		return self.username

	def __str__(self):
		return self.username

website/detail/views.py
from django.conf import settings
from django.contrib import messages
from django.core.mail import send_mail

from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404,render_to_response
from django.contrib.auth import authenticate, login, logout
# from django.core.context_processors import csrf
from django.contrib.auth.models import User



from .formsyn import PostForm
from .models import Detail

from .models import contactus
from .contactform import ContactForm

from .models import comment
from .commentform import CommentForm

from .models import stories
from .storyform import StoryForm






def index(request):
	if request.user.is_authenticated():
		return HttpResponseRedirect('/home')
	else:
		return render(request,"index.html",{})




# login section start

def Login(request):
	#c={}
	#c.update(csrf(request))
	return render_to_response('login.html')

def logIn(request):
	return render(request,"invalid.html",{})

def auth_view(request):
	username = request.POST['username']
	password = request.POST['password']
	user = authenticate(username = username, password = password)
	if user is not None:
		login(request,user)
		return HttpResponseRedirect('/home')
	else:
		return HttpResponseRedirect('/logIn')

# login section finish


def logOut(request):
	logout(request)
	return HttpResponseRedirect('/')







def details(request):
	form = PostForm(request.POST or None)
	context = {
		"form" : form,
		"username":request.user.get_username(),
	}
	return render(request,"info.html",context)


def formcheck(request):
	form = PostForm(request.POST or None)
	if form.is_valid():
		instance = form.save(commit=False)
		instance.save()
	return HttpResponseRedirect('/home')






def signup(request):
	# c={}
	# c.update(csrf(request))
	return render_to_response('signup.html')


def signcheck(request):
	username = request.POST['username']
	email = request.POST['email']
	password = request.POST['password']
	if User.objects.filter(email = email).exists() and User.objects.filter(username = username).exists():
		context = {
				"statement" : "You already have an account, so please login!!"
		}
		return render(request,"signup.html",context)
	elif User.objects.filter(username=username).exists():
		context = {
				"statement" : "Username already exist, change your username!!"
		}
		return render(request,"signup.html",context)
	elif User.objects.filter(email = email).exists():
		context = {
				"statement" : "Email is already registered, enter new email!!"
		}
		return render(request,"signup.html",context)
	
	else:
		user = User.objects.create_user(username, email, password)
		user.save()
		user = authenticate(username = username, password = password)
		login(request,user)
		subject = 'thank you'
		message = 'welcome https://docs.djangoproject.com/en/1.10/topics/email/'
		from_email = settings.EMAIL_HOST_USER
		to_list = (user.email, settings.EMAIL_HOST_USER)
		send_mail(subject,message,from_email,to_list, fail_silently = True)
		return HttpResponseRedirect('/details')







def home(request):
	if not request.user.is_authenticated():
		return HttpResponseRedirect('/login')
	else:
		context = {
			"username":request.user.get_username(),
		}
		return render(request,"home.html",context)

def gallery(request):
	if not request.user.is_authenticated():
		return HttpResponseRedirect('/login')
	else:
		context = {
			"username":request.user.get_username(),
		}
		return render(request,"gallery.html",context)

def member(request):
	if not request.user.is_authenticated():
		return HttpResponseRedirect('/login')
	else:
		queryset = Detail.objects.all()
		context = {
			"detail_list" : queryset,
			"username":request.user.get_username(),
		}
		return render(request,"member.html",context)


def feedbackmake(request):
	if not request.user.is_authenticated():
		return HttpResponseRedirect('/login')
	else:
		queryset = stories.objects.order_by('-id')
		form = StoryForm(request.POST or None)
		context = {
			"form" : form,
			"story_list" : queryset,
			"username":request.user.get_username(),
		}
		return render(request,"feedback.html",context)


def contact(request):
	if not request.user.is_authenticated():
		return HttpResponseRedirect('/login')
	else:
		form = ContactForm(request.POST or None)
		context = {
			"form" : form,
			"username":request.user.get_username(),
		}
		return render(request,"contact.html",context)


def commentmake(request):
	if not request.user.is_authenticated():
		return HttpResponseRedirect('/login')
	else:
		queryset = comment.objects.order_by('-id')
		form = CommentForm(request.POST or None)
		context = {
			"form" : form,
			"comment_list" : queryset,
			"username":request.user.get_username(),
		}
		return render(request,"comment.html",context)




def formcheck2(request):
	form = ContactForm(request.POST or None)
	if form.is_valid():
		instance = form.save(commit=False)
		instance.save()
	return HttpResponseRedirect('/feedback/')


def formcheck3(request):
	form = CommentForm(request.POST or None)
	if form.is_valid():
		instance = form.save(commit=False)
		instance.save()
	return HttpResponseRedirect('/comment/')


def formcheck4(request):
	form = StoryForm(request.POST or None)
	if form.is_valid():
		instance = form.save(commit=False)
		instance.save()
	return HttpResponseRedirect('/feedback/')

website/templates/comment.html
<!DOCTYPE html>
<html>
<head>
	

	<title>Sahabhagita</title>
	<link rel="shortcut icon" href="/static/images/favicon.png" />
	
	
	<link rel="stylesheet" href="/static/css/basic/bootstrap.css"/>
	<link rel="stylesheet" href="/static/css/basic/bootstrap.min.css"/>
	<link rel="stylesheet" href="/static/css/basic/font-awesome.min.css"/>
	<link rel="stylesheet" href="/static/css/basic/font-awesome.css"/>
	<script type="text/javascript" src="/static/css/basic/jquery-3.0.0.min.js"></script>
	<script src="/static/css/basic/sweetalert.min.js"></script> 
	<link rel="stylesheet" type="text/css" href="/static/css/basic/sweetalert.css">
	<script src="/static/css/basic/stickyfill.js"></script> 
	


	<link rel="stylesheet" type="text/css" href="/static/css/general.css">



	<script type="text/javascript" src="/static/css/basic/fancybox/jquery.fancybox.js?v=2.1.5"></script>
	<link rel="stylesheet" type="text/css" href="/static/css/basic/fancybox/jquery.fancybox.css?v=2.1.5" media="screen" />
	

	

	





	<!-- Bootstrap files start from here -->
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

	<!-- Bootstrap files ends here -->

	<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  	<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  	<script src="/static/css/basic/stickyfill.js"></script> 

	
	<script>
		$(function(){
  			$('#sidebar').Stickyfill();
		});

		function myFunction() {
    		sweetAlert("Here's a message!","If you are alumni than please sign in for enter in the website");
		}

	</script>



</head>
<body>
	



	<nav class="navbar" style="padding-top : 10px; background : rgba(245,245,255,0.9); padding-bottom : 10px; margin-bottom: 0px; box-shadow: inset 0 0 10px #000000;">
		<div class="container-fluid">
		    <div class="navbar-header">
		    	<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
		        	<span class="icon-bar"></span>
		        	<span class="icon-bar"></span>
		        	<span class="icon-bar"></span>
		      	</button>
		      	<a href=""><img class="img-responsive logo" src="/static/images/logo1.png" width="400px" alt = "logo" style="margin-top : 5px; margin-left : 50px;" /></a>
		    </div>

		    <div class="collapse navbar-collapse" id="myNavbar" style="float: right; ">   
		        <nav class="nav navbar-nav">
		        	<li><a href="../home" class="log"><p class="signin" style="border-radius: 5px 5px;">Welcome</p></a></li>
		        	<li><a href="../gallery" class="log"><p class="signin" style="border-radius: 5px 5px;">Gallery</p></a></li>
		        	<li><a href="../members" class="log"><p class="signin" style="border-radius: 5px 5px; ">Members</p></a></li>
		        	<li><a href="../feedback" class="log"><p class="signin" style="border-radius: 5px 5px; background: rgb(128,128,255);">Discussion</p></a></li>
					<li><a href="../logout" class="log"><p class="signup">Logout</p></a></li>
					<li><a href="" class="log"><p class="signin">{{username}}</p></a></li>
				</nav>
		    </div>
	    </div>
	  </div>
	</nav>
	

	<div class="cont">
		<div class="row">
			<div class="container-fluid">
				
				<div class="sidebar" id="sidebar" style="background : rgba(0,0,125,0.8); width: 25%; float: left;">
					
					<div class="topic" style="padding-top : 30px; height : 100vh;">
						<p class="tag" style="margin-top : 30px; text-align : right;"><a class="welcome">ALUMNI CORNER</a></p><hr class="mainline">
						<p class="tag" style="cursor : pointer; "><a href="../feedback/" id="event1" class="main"><i class="fa fa-newspaper-o" aria-hidden="true" style="margin-right: 10px; "></i>PARTICIPATE</a></p>
						<p class="tag" style="cursor : pointer;"><a href="../comment/" id="event2" class="main" style=" color: white;"><i class="fa fa-comment" aria-hidden="true" style="margin-right: 10px; "></i>COMMENTS</a></p>
						<p class="tag" style="cursor : pointer;"><a href="../contact/" id="event3" class="main"><i class="fa fa-phone" aria-hidden="true" style="margin-right: 10px;"></i>CONTACT US</a></p>
						
						


						<div class="topic" style="padding-top : 10px;">
							<p class="tag" style="margin-top : 30px; text-align : right;"><a href="#" class="welcome">CONTACT US</a></p><hr class="mainline">
							<p class="tag1" style="text-align : left; margin-bottom: 0px; "><i class="fa fa-envelope" aria-hidden="true" style="margin-right: 10px; "></i>sahabhagita16@gmail.com</p>
							
							<div class="col-md-8 col-md-offset-2" style="margin-bottom: 50px; float: center; ">
								<a href="https://www.facebook.com/Sahabhagita/?__mref=message_bubble" target="_blank"><i class="fa fa-facebook-square icon"></i></a>
								<a href=">https://twitter.com/SahabhagitaOrg" target="_blank"><i class="fa fa-twitter-square icon"></i></a>
								<a href="" target="_blank"><i class="fa fa-youtube-square icon"></i></a>
							</div>

							<p class="tag" style="text-align: center; color: white; ">2016 &#169; Sahabhagita</p>
							<p class="tag" style="text-align: center; color: white; ">Created by <a href="https://itsshivam.github.io/" target="_blank" style="color : rgb(200,200,255);">Shivam Pal</a></p>
						</div>
					</div>
				</div>







				<div class="mainbar">

				<div class="col-md-12 event3" id="contact">
					<div class="topic" style="padding-top : 100px; min-height : 100vh;">
						<div class="vision col-md-10 motive" style="margin-bottom : 50px; padding-bottom: 0px; ">
							<div class="col-md-10 col-md-offset-1">
								<h6 class="heavi"><img class="img-responsive" src="/static/images/arrow1.png" width="100x" alt = "bullet" style="float: left; margin-right: 10px; " />Express Your Views<img class="img-responsive" src="/static/images/arrow.png" width="100x" alt = "bullet" style="float: right; margin-right: 10px; " /></h6><hr class="style2">
							</div>



							<div class="col-md-10 col-md-offset-1" style="margin-top : 20px;">
							
								
								<form action="../Comment/" method="post" name="myform" onsubmit="return(validate())">{% csrf_token %}

									<input type="hidden" class="form-control" name="username" id="usename" value="{{username}}" readonly >
						
									<div class="col-md-12">
										<div class="col-md-3 form"><label for="message"><i class="fa fa-envelope" aria-hidden="true" style="margin-right: 10px; "></i>Comment&#42</label></div>
										<div class="col-md-8 col-md-offset-1"><textarea rows="4" class="form-control" name="comment" id="id_comment" style="color : rgb(50,50,255); border-radius: 5px 5px; border : 1px solid rgb(128,128,255);"></textarea></div>
									</div>
									<div class="col-md-12" style="margin-top : 10px; margin-bottom : 0px;">
										<div class="col-md-3 col-md-offset-4"><input type="submit" name="submit" value="SUBMIT" /></div>
									</div>
								</form>
								
							</div>


							<div class="col-md-10 col-md-offset-1" style="margin-top : 15px;  margin-bottom : 20px;">
								{% for obj in comment_list %}
								<div style="margin-top: 20px; ">
									<div class="col-md-12">
										<p class="mem" style="color: rgb(60,60,255); font-size: 20px; margin-right: 5px; "><img class="img-responsive" src="/static/images/user1.png" width="25x" alt = "bullet" style="float: left; margin-right: 10px; " />{{obj.username}}</p>
										<p class="mem" style="color: rgb(100,100,255); font-size: 13px;">{{obj.timestamp}}</p>
									</div>
									<div class="col-md-10 col-md-offset-1">
										<p class="vision" style="font-size: 16px; ">{{ obj.comment | linebreaks }}</p>
									</div>
								</div>
								
								{% endfor %}
							</div>


							
							
						</div>
					</div>
				</div>

				<div class="col-md-12 foot" id="footer" style="background-color: rgba(0,0,125,0.8)">
					<div class="col-md-10 col-md-offset-1" style="float: center;">
						<p class="intro" style="text-align:  center; color: white">
							<i class="fa fa-envelope" aria-hidden="true" style="margin-right: 10px; "></i>sahabhagita@gmail.com,
							<a href="https://www.facebook.com/Sahabhagita/?__mref=message_bubble" target="_blank"><i class="fa fa-facebook-square icon"></i></a>
							<a href=">https://twitter.com/SahabhagitaOrg" target="_blank"><i class="fa fa-twitter-square icon"></i></a>
							<a href="" target="_blank"><i class="fa fa-youtube-square icon"></i></a>
						</p>
						<p class="intro" style="text-align: center; color: white;">2016 &#169; Sahabhagita</p>
						<p class="intro" style="text-align: center; color: white;">Created by <a href="https://itsshivam.github.io/" target="_blank" style="color : rgb(200,200,255);">Shivam Pal</a></p>
					</div>
						</div>
				</div>




				</div>
			</div>
		</div>
	</div>




</body>
</html>

website/templates/contact.html
<!DOCTYPE html>
<html>
<head>
	

	<title>Sahabhagita</title>
	<link rel="shortcut icon" href="/static/images/favicon.png" />
	
	
	<link rel="stylesheet" href="/static/css/basic/bootstrap.css"/>
	<link rel="stylesheet" href="/static/css/basic/bootstrap.min.css"/>
	<link rel="stylesheet" href="/static/css/basic/font-awesome.min.css"/>
	<link rel="stylesheet" href="/static/css/basic/font-awesome.css"/>
	<script type="text/javascript" src="/static/css/basic/jquery-3.0.0.min.js"></script>
	<script src="/static/css/basic/sweetalert.min.js"></script> 
	<link rel="stylesheet" type="text/css" href="/static/css/basic/sweetalert.css">
	<script src="/static/css/basic/stickyfill.js"></script> 
	


	<link rel="stylesheet" type="text/css" href="/static/css/general.css">



	<script type="text/javascript" src="/static/css/basic/fancybox/jquery.fancybox.js?v=2.1.5"></script>
	<link rel="stylesheet" type="text/css" href="/static/css/basic/fancybox/jquery.fancybox.css?v=2.1.5" media="screen" />
	

	

	





	<!-- Bootstrap files start from here -->
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

	<!-- Bootstrap files ends here -->

	<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  	<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  	<script src="/static/css/basic/stickyfill.js"></script> 


	
	<script>
		$(function(){
  			$('#sidebar').Stickyfill();
		});

		function myFunction() {
    		sweetAlert("Here's a message!","If you are alumni than please sign in for enter in the website");
		}

		
	</script>



</head>
<body>
	



	<nav class="navbar" style="padding-top : 10px; background : rgba(245,245,255,0.9); padding-bottom : 10px; margin-bottom: 0px; box-shadow: inset 0 0 10px #000000;">
		<div class="container-fluid">
		    <div class="navbar-header">
		    	<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
		        	<span class="icon-bar"></span>
		        	<span class="icon-bar"></span>
		        	<span class="icon-bar"></span>
		      	</button>
		      	<a href=""><img class="img-responsive logo" src="/static/images/logo1.png" width="400px" alt = "logo" style="margin-top : 5px; margin-left : 50px;" /></a>
		    </div>

		    <div class="collapse navbar-collapse" id="myNavbar" style="float: right; ">   
		        <nav class="nav navbar-nav">
		        	<li><a href="../home" class="log"><p class="signin" style="border-radius: 5px 5px;">Welcome</p></a></li>
		        	<li><a href="../gallery" class="log"><p class="signin" style="border-radius: 5px 5px;">Gallery</p></a></li>
		        	<li><a href="../members" class="log"><p class="signin" style="border-radius: 5px 5px; ">Members</p></a></li>
		        	<li><a href="../feedback" class="log"><p class="signin" style="border-radius: 5px 5px; background: rgb(128,128,255);">Discussion</p></a></li>
					<li><a href="../logout" class="log"><p class="signup">Logout</p></a></li>
					<li><a href="" class="log"><p class="signin">{{username}}</p></a></li>
				</nav>
		    </div>
	    </div>
	  </div>
	</nav>
	

	<div class="cont">
		<div class="row">
			<div class="container-fluid">
				
				<div class="sidebar" id="sidebar" style="background : rgba(0,0,125,0.8); width: 25%; float: left;">
						
					<div class="topic" style="padding-top : 30px; height : 100vh;">
						<p class="tag" style="margin-top : 30px; text-align : right;"><a class="welcome">ALUMNI CORNER</a></p><hr class="mainline">
						<p class="tag" style="cursor : pointer;"><a href="../feedback/" id="event1" class="main"><i class="fa fa-newspaper-o" aria-hidden="true" style="margin-right: 10px; "></i>PARTICIPATE</a></p>
						<p class="tag" style="cursor : pointer;"><a href="../comment/" id="event2" class="main"><i class="fa fa-comment" aria-hidden="true" style="margin-right: 10px; "></i>COMMENTS</a></p>
						<p class="tag" style="cursor : pointer;"><a href="../contact/" id="event3" class="main" style=" color: white;"><i class="fa fa-phone" aria-hidden="true" style="margin-right: 10px;"></i>CONTACT US</a></p>
						
					


						<div class="topic" style="padding-top : 10px;">
							<p class="tag" style="margin-top : 30px; text-align : right;"><a href="#" class="welcome">CONTACT US</a></p><hr class="mainline">
							<p class="tag1" style="text-align : left; margin-bottom: 0px; "><i class="fa fa-envelope" aria-hidden="true" style="margin-right: 10px; "></i>sahabhagita16@gmail.com</p>
							
							<div class="col-md-8 col-md-offset-2" style="margin-bottom: 50px; float: center; ">
								<a href="https://www.facebook.com/Sahabhagita/?__mref=message_bubble" target="_blank"><i class="fa fa-facebook-square icon"></i></a>
								<a href=">https://twitter.com/SahabhagitaOrg" target="_blank"><i class="fa fa-twitter-square icon"></i></a>
								<a href="" target="_blank"><i class="fa fa-youtube-square icon"></i></a>
							</div>

							<p class="tag" style="text-align: center; color: white; ">2016 &#169; Sahabhagita</p>
							<p class="tag" style="text-align: center; color: white; ">Created by <a href="https://itsshivam.github.io/" target="_blank" style="color : rgb(200,200,255);">Shivam Pal</a></p>
						</div>


					</div>
				</div>

				<div class="mainbar">


					<div class="col-md-12 event3" id="contact">
						<div class="topic" style="padding-top : 100px; min-height : 100vh;">
							<div class="vision col-md-10 motive" style="margin-bottom : 50px; padding-bottom: 0px; ">
								<div class="col-md-10 col-md-offset-1">
									<h6 class="heavi"><img class="img-responsive" src="/static/images/arrow1.png" width="100x" alt = "bullet" style="float: left; margin-right: 10px; " />Contact Us<img class="img-responsive" src="/static/images/arrow.png" width="100x" alt = "bullet" style="float: right; margin-right: 10px; " /></h6><hr class="style2">
								</div>
								
								<div class="col-md-10 col-md-offset-1" style="margin-top : 20px;">
								

								<form action="../Contact/" method="post" name="myform" onsubmit="return(validate())">{% csrf_token %}


									<p><div class="col-md-12">
										<div class="col-md-3 form"><label for="username"><i class="fa fa-user" aria-hidden="true" style="margin-right: 10px; "></i>Username</label></div>
										<div class="col-md-8 col-md-offset-1"><input type="text" class="form-control" name="username" id="usename" value="{{username}}" readonly style="color : rgb(50,50,255); border-radius: 5px 5px; border : 1px solid rgb(128,128,255); background: white; " ></div>
									</div></p>
				

						
									<div class="col-md-12">
										<div class="col-md-3 form"><label for="message"><i class="fa fa-envelope" aria-hidden="true" style="margin-right: 10px; "></i>Message&#42</label></div>
										<div class="col-md-8 col-md-offset-1"><textarea rows="5" class="form-control" name="message" id="id_message" style="color : rgb(50,50,255); border-radius: 5px 5px; border : 1px solid rgb(128,128,255);"></textarea></div>
									</div>

									
									<div class="col-md-12" style="margin-top : 30px; margin-bottom : 20px;">
										<div class="col-md-3 col-md-offset-4"><input type="submit" name="submit" value="SUBMIT" /></div>
									</div>

									
								</form>
							</div>
						</div>
					</div>
				</div>

				<div class="col-md-12 foot" id="footer" style="background-color: rgba(0,0,125,0.8)">
					<div class="col-md-10 col-md-offset-1" style="float: center;">
						<p class="intro" style="text-align:  center; color: white">
							<i class="fa fa-envelope" aria-hidden="true" style="margin-right: 10px; "></i>sahabhagita@gmail.com,
							<a href="https://www.facebook.com/Sahabhagita/?__mref=message_bubble" target="_blank"><i class="fa fa-facebook-square icon"></i></a>
							<a href=">https://twitter.com/SahabhagitaOrg" target="_blank"><i class="fa fa-twitter-square icon"></i></a>
							<a href="" target="_blank"><i class="fa fa-youtube-square icon"></i></a>
						</p>
						<p class="intro" style="text-align: center; color: white;">2016 &#169; Sahabhagita</p>
						<p class="intro" style="text-align: center; color: white;">Created by <a href="https://itsshivam.github.io/" target="_blank" style="color : rgb(200,200,255);">Shivam Pal</a></p>
					</div>
						</div>
				</div>




				</div>
			</div>
		</div>
	</div>




</body>
</html>